---
- name: Ensure storage directory
  file:
    state: directory
    path: "{{ vmagent_storage_dir }}"
    mode: 0755
    owner: root
    group: root

- name: Ensure scrape_configs directory
  file:
    state: directory
    path: "{{ vmagent_config_dir }}/scrape_configs"
    mode: 0755
    owner: root
    group: root

- name: Show configuration
  debug:
    var: prometheus_config
  tags:
    - show_config

- name: Ensure configuration file
  template:
    src: prometheus.yml.j2
    dest: "{{ vmagent_config_dir }}/prometheus.yml"
    mode: 0755
    owner: root
    group: root
  notify:
    - Reload vmagent

- name: Find scrape_configs files
  find:
    paths: "{{ vmagent_config_dir }}/scrape_configs"
    patterns: "*.yml"
  register: list_of_scrape_files

- name: Select names of scrape_config files
  set_fact:
    list_of_scrape_filenames: "{{ list_of_scrape_filenames|default([]) }} + [ '{{ item.path|basename }}' ]"
  with_items: "{{ list_of_scrape_files.files }}"

- name: debug
  debug: 
    msg: "{{ vars[item][0]['filename'] }}"
  with_items: "{{ vmagent_additional_configs }}"

- name: Set list of names
  set_fact:
    list_of_filenames_to_add: "{{ list_of_filenames_to_add|default([]) }} + [ '{{ vars[item].filename }}' ]"
  with_items: "{{ vmagent_additional_configs }}"

- name: Clear scrape_configs directory
  file:
    path: "{{ vmagent_config_dir }}/scrape_configs/{{ item }}"
    state: absent
  with_items: "{{ list_of_scrape_filenames | default([]) | difference(list_of_filenames_to_add) }}"

- name: Ensure additional configuration files
  copy:
    content: "{{ item.data }}"
    dest: "{{ vmagent_config_dir }}/scrape_configs/{{ vars[item].filename }}"
    mode: 0755
    owner: root
    group: root
  with_items: "{{ vmagent_additional_configs }}"
  notify:
    - Reload vmagent

- name: Start docker vmagent container
  docker_compose:
    state: present
    project_name: vmagent
    definition:
      version: '2'
      services:
        vmagent:
          image: "{{ vmagent_docker_image }}"
          container_name: "{{ vmagent_container_name }}"
          command: "{{ vmagent_command }}"
          ports:
            - "{{ vmagent_address }}:8429:8429"
          volumes:
            - "{{ vmagent_storage_dir }}:/vmagentdata"
            - "{{ vmagent_config_dir }}/prometheus.yml:/etc/prometheus/prometheus.yml"
            - "{{ vmagent_config_dir }}/scrape_configs:/etc/prometheus/scrape_configs"
          hostname: "{{ vmagent_container_name }}"
          restart: always
          labels: "{{ vmagent_docker_labels }}"
          extra_hosts: "{{ vmagent_extra_hosts }}"
      networks:
        default:
          external:
            name: "{{ vmagent_docker_network_name }}"
